version: '3.8'

services:
  reverse-fe-proxy:
    build:
      context: ./reverse-fe-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./logs/reverse-fe-proxy:/var/log/nginx

  nginx-bff-srv01:
    build:
      context: ./nginx-bff-srv01
    ports:
      - "8081:8081"
    volumes:
      - ./logs/nginx-bff-srv01:/var/log/nginx

  nginx-bff-srv02:
    build:
      context: ./nginx-bff-srv02
    ports:
      - "8082:8082"
    volumes:
      - ./logs/nginx-bff-srv02:/var/log/nginx

  nginx-fluent-bit-log:
    build:
      context: ./nginx-fluent-bit-log
    ports:
      - "8083:8083"
    volumes:
      - ./logs/nginx-fluent-bit-log:/var/log/nginx

  python-be-app01:
    build:
      context: ./python-be-app01
    ports:
      - "5001:5001"

  python-be-app02:
    build:
      context: ./python-be-app02
    ports:
      - "5002:5002"
